# Script simplificado para limpiar y actualizar ARB files

$langFiles = @{
    'ar' = 'إدارة المدفوعات","noAccounts":"لا توجد حسابات محفوظة","addAccount":"إضافة حساب","deleteAccountTitle":"حذف الحساب","deleteAccountContent":"هل تريد حذف \"{alias}\"؟","deleteAction":"حذف","newAccount":"حساب جديد","editAccount":"تعديل الحساب","aliasLabel":"الاسم المستعار (اسم التعريف)","bankLabel":"البنك","ciLabel":"الهوية / RIF","phoneLabel":"الهاتف","accountNumberLabel":"رقم الحساب (20 رقماً)","pagoMovil":"الدفع عبر الهاتف","bankTransfer":"تحويل بنكي","requiredField":"حقل مطلوب","selectBank":"اختر بنكاً","onlyAmount":"نص فقط / المبلغ","configureAccounts":"إعداد الحسابات","configureAccountsDesc":"أضف بياناتك للمشاركة بسرعة","yourAccounts":"حساباتك","manageAccounts":"إدارة الحسابات","transferData":"بيانات التحويل","nameLabel":"الاسم","accountLabel":"الحساب","actionCopy":"نسخ","actionShare":"مشاركة","amountLabel":"المبلغ'
    'de' = 'Zahlungsverwaltung","noAccounts":"Keine gespeicherten Konten","addAccount":"Konto hinzufügen","deleteAccountTitle":"Konto löschen","deleteAccountContent":"Möchten Sie \"{alias}\" löschen?","deleteAction":"Löschen","newAccount":"Neues Konto","editAccount":"Konto bearbeiten","aliasLabel":"Alias (Identifikationsname)","bankLabel":"Bank","ciLabel":"ID / RIF","phoneLabel":"Telefon","accountNumberLabel":"Kontonummer (20 Ziffern)","pagoMovil":"Mobiles Bezahlen","bankTransfer":"Überweisung","requiredField":"Pflichtfeld","selectBank":"Bank auswählen","onlyAmount":"Nur Text / Betrag","configureAccounts":"Konten konfigurieren","configureAccountsDesc":"Fügen Sie Ihre Daten hinzu, um schnell zu teilen","yourAccounts":"IHRE KONTEN","manageAccounts":"Konten verwalten","transferData":"Überweisungsdaten","nameLabel":"Name","accountLabel":"Konto","actionCopy":"Kopieren","actionShare":"Teilen","amountLabel":"Betrag'
    'fr' = 'Gestion des Paiements","noAccounts":"Aucun compte enregistré","addAccount":"Ajouter un compte","deleteAccountTitle":"Supprimer le compte","deleteAccountContent":"Voulez-vous supprimer \"{alias}\" ?","deleteAction":"Supprimer","newAccount":"Nouveau compte","editAccount":"Modifier le compte","aliasLabel":"Alias (Nom d''identification)","bankLabel":"Banque","ciLabel":"ID / RIF","phoneLabel":"Téléphone","accountNumberLabel":"Numéro de compte (20 chiffres)","pagoMovil":"Paiement Mobile","bankTransfer":"Virement","requiredField":"Champ obligatoire","selectBank":"Sélectionnez une banque","onlyAmount":"Texte uniquement / Montant","configureAccounts":"Configurer les comptes","configureAccountsDesc":"Ajoutez vos données pour partager rapidement","yourAccounts":"VOS COMPTES","manageAccounts":"Gérer les comptes","transferData":"Données de virement","nameLabel":"Nom","accountLabel":"Compte","actionCopy":"Copier","actionShare":"Partager","amountLabel":"Montant'
    'hi' = 'भुगतान प्रबंधन","noAccounts":"कोई खाता सहेजा नहीं गया","addAccount":"खाता जोड़ें","deleteAccountTitle":"खाता हटाएं","deleteAccountContent":"क्या आप \"{alias}\" को हटाना चाहते हैं?","deleteAction":"हटाएं","newAccount":"नया खाता","editAccount":"खाता संपादित करें","aliasLabel":"उपनाम (पहचान नाम)","bankLabel":"बैंक","ciLabel":"आईडी / RIF","phoneLabel":"फ़ोन","accountNumberLabel":"खाता संख्या (20 अंक)","pagoMovil":"मोबाइल भुगतान","bankTransfer":"बैंक हस्तांतरण","requiredField":"आवश्यक फ़ील्ड","selectBank":"बैंक चुनें","onlyAmount":"केवल पाठ / राशि","configureAccounts":"खाते कॉन्फ़िगर करें","configureAccountsDesc":"तेज़ी से साझा करने के लिए अपना डेटा जोड़ें","yourAccounts":"आपके खाते","manageAccounts":"खाते प्रबंधित करें","transferData":"हस्तांतरण डेटा","nameLabel":"नाम","accountLabel":"खाता","actionCopy":"कॉपी करें","actionShare":"साझा करें","amountLabel":"राशि'
    'id' = 'Manajemen Pembayaran","noAccounts":"Tidak ada akun tersimpan","addAccount":"Tambah Akun","deleteAccountTitle":"Hapus Akun","deleteAccountContent":"Apakah Anda ingin menghapus \"{alias}\"?","deleteAction":"Hapus","newAccount":"Akun Baru","editAccount":"Edit Akun","aliasLabel":"Alias (Nama Identifikasi)","bankLabel":"Bank","ciLabel":"ID / RIF","phoneLabel":"Telepon","accountNumberLabel":"Nomor Rekening (20 digit)","pagoMovil":"Pembayaran Seluler","bankTransfer":"Transfer","requiredField":"Wajib diisi","selectBank":"Pilih bank","onlyAmount":"Hanya Teks / Jumlah","configureAccounts":"Konfigurasi Akun","configureAccountsDesc":"Tambahkan data untuk berbagi cepat","yourAccounts":"AKUN ANDA","manageAccounts":"Kelola Akun","transferData":"Data Transfer","nameLabel":"Nama","accountLabel":"Rekening","actionCopy":"Salin","actionShare":"Bagikan","amountLabel":"Jumlah'
    'it' = 'Gestione Pagamenti","noAccounts":"Nessun conto salvato","addAccount":"Aggiungi Conto","deleteAccountTitle":"Elimina Conto","deleteAccountContent":"Vuoi eliminare \"{alias}\"?","deleteAction":"Elimina","newAccount":"Nuovo Conto","editAccount":"Modifica Conto","aliasLabel":"Alias (Nome Identificativo)","bankLabel":"Banca","ciLabel":"ID / RIF","phoneLabel":"Telefono","accountNumberLabel":"Numero di Conto (20 cifre)","pagoMovil":"Pagamento Mobile","bankTransfer":"Bonifico","requiredField":"Campo obbligatorio","selectBank":"Seleziona una banca","onlyAmount":"Solo Testo / Importo","configureAccounts":"Configura Conti","configureAccountsDesc":"Aggiungi i tuoi dati per condividere velocemente","yourAccounts":"I TUOI CONTI","manageAccounts":"Gestisci Conti","transferData":"Dati Bonifico","nameLabel":"Nome","accountLabel":"Conto","actionCopy":"Copia","actionShare":"Condividi","amountLabel":"Importo'
    'ja' = '支払い管理","noAccounts":"保存されたアカウントはありません","addAccount":"アカウントを追加","deleteAccountTitle":"アカウントを削除","deleteAccountContent":"\"{alias}\" を削除しますか？","deleteAction":"削除","newAccount":"新しいアカウント","editAccount":"アカウントを編集","aliasLabel":"エイリアス（識別名）","bankLabel":"銀行","ciLabel":"ID / RIF","phoneLabel":"電話番号","accountNumberLabel":"口座番号（20桁）","pagoMovil":"モバイル決済","bankTransfer":"振込","requiredField":"必須項目","selectBank":"銀行を選択","onlyAmount":"テキストのみ / 金額","configureAccounts":"アカウント設定","configureAccountsDesc":"データを追加して素早く共有","yourAccounts":"あなたのアカウント","manageAccounts":"アカウント管理","transferData":"振込データ","nameLabel":"名前","accountLabel":"口座","actionCopy":"コピー","actionShare":"共有","amountLabel":"金額'
    'ko' = '결제 관리","noAccounts":"저장된 계정 없음","addAccount":"계정 추가","deleteAccountTitle":"계정 삭제","deleteAccountContent":"\"{alias}\" 계정을 삭제하시겠습니까?","deleteAction":"삭제","newAccount":"새 계정","editAccount":"계정 수정","aliasLabel":"별칭 (식별 이름)","bankLabel":"은행","ciLabel":"신분증 / RIF","phoneLabel":"전화번호","accountNumberLabel":"계좌 번호 (20자리)","pagoMovil":"모바일 결제","bankTransfer":"이체","requiredField":"필수 항목","selectBank":"은행 선택","onlyAmount":"텍스트만 / 금액","configureAccounts":"계정 설정","configureAccountsDesc":"빠른 공유를 위해 데이터 추가","yourAccounts":"내 계정","manageAccounts":"계정 관리","transferData":"이체 정보","nameLabel":"이름","accountLabel":"계좌","actionCopy":"복사","actionShare":"공유","amountLabel":"금액'
    'pt' = 'Gerenciamento de Pagamentos","noAccounts":"Nenhuma conta salva","addAccount":"Adicionar Conta","deleteAccountTitle":"Excluir Conta","deleteAccountContent":"Deseja excluir \"{alias}\"?","deleteAction":"Excluir","newAccount":"Nova Conta","editAccount":"Editar Conta","aliasLabel":"Apelido (Nome de Identificação)","bankLabel":"Banco","ciLabel":"ID / RIF","phoneLabel":"Telefone","accountNumberLabel":"Número da Conta (20 dígitos)","pagoMovil":"Pagamento Móvel","bankTransfer":"Transferência","requiredField":"Campo obrigatório","selectBank":"Selecione um banco","onlyAmount":"Apenas Texto / Valor","configureAccounts":"Configurar Contas","configureAccountsDesc":"Adicione seus dados para compartilhar rápido","yourAccounts":"SUAS CONTAS","manageAccounts":"Gerenciar Contas","transferData":"Dados de Transferência","nameLabel":"Nome","accountLabel":"Conta","actionCopy":"Copiar","actionShare":"Compartilhar","amountLabel":"Valor'
    'ru' = 'Управление платежами","noAccounts":"Нет сохраненных счетов","addAccount":"Добавить счет","deleteAccountTitle":"Удалить счет","deleteAccountContent":"Вы хотите удалить \"{alias}\"?","deleteAction":"Удалить","newAccount":"Новый счет","editAccount":"Редактировать счет","aliasLabel":"Псевдоним (Имя для идентификации)","bankLabel":"Банк","ciLabel":"ID / RIF","phoneLabel":"Телефон","accountNumberLabel":"Номер счета (20 цифр)","pagoMovil":"Мобильный платеж","bankTransfer":"Перевод","requiredField":"Обязательное поле","selectBank":"Выберите банк","onlyAmount":"Только текст / Сумма","configureAccounts":"Настроить счета","configureAccountsDesc":"Добавьте свои данные для быстрой отправки","yourAccounts":"ВАШИ СЧЕТА","manageAccounts":"Управление счетами","transferData":"Данные перевода","nameLabel":"Имя","accountLabel":"Счет","actionCopy":"Копировать","actionShare":"Поделиться","amountLabel":"Сумма'
    'tr' = 'Ödeme Yönetimi","noAccounts":"Kayıtlı hesap yok","addAccount":"Hesap Ekle","deleteAccountTitle":"Hesabı Sil","deleteAccountContent":"\"{alias}\" hesabını silmek istiyor musunuz?","deleteAction":"Sil","newAccount":"Yeni Hesap","editAccount":"Hesabı Düzenle","aliasLabel":"Takma Ad (Tanımlama Adı)","bankLabel":"Banka","ciLabel":"Kimlik / RIF","phoneLabel":"Telefon","accountNumberLabel":"Hesap Numarası (20 hane)","pagoMovil":"Mobil Ödeme","bankTransfer":"Transfer","requiredField":"Zorunlu alan","selectBank":"Bir banka seçin","onlyAmount":"Sadece Metin / Tutar","configureAccounts":"Hesapları Yapılandır","configureAccountsDesc":"Hızlı paylaşım için verilerinizi ekleyin","yourAccounts":"HESAPLARINIZ","manageAccounts":"Hesapları Yönet","transferData":"Transfer Verileri","nameLabel":"İsim","accountLabel":"Hesap","actionCopy":"Kopyala","actionShare":"Paylaş","amountLabel":"Tutar'
    'vi' = 'Quản lý thanh toán","noAccounts":"Không có tài khoản đã lưu","addAccount":"Thêm tài khoản","deleteAccountTitle":"Xóa tài khoản","deleteAccountContent":"Bạn có muốn xóa \"{alias}\" không?","deleteAction":"Xóa","newAccount":"Tài khoản mới","editAccount":"Chỉnh sửa tài khoản","aliasLabel":"Biệt danh (Tên định danh)","bankLabel":"Ngân hàng","ciLabel":"ID / RIF","phoneLabel":"Điện thoại","accountNumberLabel":"Số tài khoản (20 chữ số)","pagoMovil":"Thanh toán di động","bankTransfer":"Chuyển khoản","requiredField":"Trường bắt buộc","selectBank":"Chọn ngân hàng","onlyAmount":"Chỉ văn bản / Số tiền","configureAccounts":"Cấu hình tài khoản","configureAccountsDesc":"Thêm dữ liệu để chia sẻ nhanh","yourAccounts":"TÀI KHOẢN CỦA BẠN","manageAccounts":"Quản lý tài khoản","transferData":"Dữ liệu chuyển khoản","nameLabel":"Tên","accountLabel":"Tài khoản","actionCopy":"Sao chép","actionShare":"Chia sẻ","amountLabel":"Số tiền'
    'zh' = '支付管理","noAccounts":"没有保存的账户","addAccount":"添加账户","deleteAccountTitle":"删除账户","deleteAccountContent":"您确定要删除\"{alias}\"吗？","deleteAction":"删除","newAccount":"新账户","editAccount":"编辑账户","aliasLabel":"别名（识别名称）","bankLabel":"银行","ciLabel":"身份证 / RIF","phoneLabel":"电话","accountNumberLabel":"银行账号（20位）","pagoMovil":"移动支付","bankTransfer":"转账","requiredField":"必填项","selectBank":"选择银行","onlyAmount":"仅文本/金额","configureAccounts":"配置账户","configureAccountsDesc":"添加您的资料以便快速分享","yourAccounts":"您的账户","manageAccounts":"管理账户","transferData":"转账资料","nameLabel":"姓名","accountLabel":"账号","actionCopy":"复制","actionShare":"分享","amountLabel":"金额'
}

foreach ($lang in $langFiles.Keys) {
    $file = "lib/l10n/app_$lang.arb"
    if (Test-Path $file) {
        # Leer contenido
        $content = Get-Content $file -Raw -Encoding UTF8
        
        # Encontrar el índice de "shareMessage" y cortar todo después
        $index = $content.LastIndexOf('"shareMessage"')
        if ($index -gt 0) {
            # Encontrar el final de la línea shareMessage
            $endQuote = $content.IndexOf('"', $content.IndexOf('https', $index) + 100)
            if ($endQuote -gt 0) {
                # Cortar hasta después del shareMessage
                $baseContent = $content.Substring(0, $endQuote + 1)
                # Agregar las nuevas traducciones
                $newContent = $baseContent + ",`r`n  `"paymentSettings`": `"" + $langFiles[$lang] + "`r`n}"
                # Guardar
                [System.IO.File]::WriteAllText($file, $newContent, [System.Text.UTF8Encoding]::new($false))
                Write-Host "✓ $lang actualizado" -ForegroundColor Green
            }
        }
    }
}

Write-Host "`n¡Completado!" -ForegroundColor Cyan
