
import os
import json

files = {
    "app_de.arb": {
        "@@locale": "de",
        "appTitle": "BCV Rechner",
        "settings": "Einstellungen",
        "general": "Allgemein",
        "storageNetwork": "Speicher & Netzwerk",
        "storageNetworkSubtitle": "Cache und Updates verwalten",
        "language": "Sprache",
        "information": "Informationen",
        "aboutApp": "Über die App",
        "aboutAppSubtitle": "Version, Entwickler und Lizenzen",
        "forceUpdate": "Update erzwingen",
        "forceUpdateSubtitle": "Kurse von API aktualisieren",
        "clearCache": "Cache leeren",
        "clearCacheSubtitle": "Lokal gespeicherte Daten löschen",
        "cancel": "Abbrechen",
        "close": "Schließen",
        "updatingRates": "Kurse werden aktualisiert...",
        "cacheCleared": "Cache geleert",
        "developer": "Entwickler",
        "dataSource": "Datenquelle",
        "legalNotice": "Rechtliche Hinweise",
        "legalNoticeText": "Diese App vertritt KEINE Regierungs- oder Bankbehörde. Wir sind nicht mit der Zentralbank von Venezuela verbunden. Die Daten werden über eine API abgerufen, die die offizielle BCV-Website abfragt. Die Nutzung der Informationen liegt in der alleinigen Verantwortung des Benutzers.",
        "openSourceLicenses": "Open-Source-Lizenzen",
        "version": "Version",
        "becomePro": "Werde PRO!",
        "proUser": "Du bist ein PRO-Benutzer!",
        "getPro": "PRO holen für",
        "oneTimePayment": "(Einmalige Zahlung auf Lebenszeit)",
        "restorePurchases": "Einkäufe wiederherstellen",
        "benefitAds": "Keine Werbung",
        "benefitAdsDesc": "Genieße eine saubere Oberfläche ohne Unterbrechungen.",
        "benefitPdf": "Sofortiger Export",
        "benefitPdfDesc": "Erstelle Verlauf-PDFs ohne Videoanzeigen.",
        "benefitSpeed": "Maximale Geschwindigkeit",
        "benefitSpeedDesc": "Flüssigere Navigation und weniger Batterieverbrauch.",
        "benefitSupport": "Projekt unterstützen",
        "benefitSupportDesc": "Hilf uns, das Tool weiter zu verbessern.",
        "usd": "US-Dollar",
        "eur": "Euro",
        "ves": "Bolivar",
        "history": "Verlauf",
        "historyRates": "Kursverlauf",
        "start": "Start",
        "end": "Ende",
        "generatePdf": "PDF generieren",
        "watchAd": "Werbung ansehen zum Entsperren",
        "loadingAd": "Werbung lädt...",
        "errorAd": "Fehler beim Laden",
        "today": "Heute",
        "tomorrow": "Morgen",
        "officialRate": "Offizieller Kurs",
        "customRate": "Benutzerdef. Kurs",
        "convert": "Konvertieren"
    },
    "app_it.arb": {
        "@@locale": "it",
        "appTitle": "Calcolatrice BCV",
        "settings": "Impostazioni",
        "general": "Generale",
        "storageNetwork": "Archiviazione e Rete",
        "storageNetworkSubtitle": "Gestisci cache e aggiornamenti",
        "language": "Lingua",
        "information": "Informazioni",
        "aboutApp": "Informazioni sull'App",
        "aboutAppSubtitle": "Versione, sviluppatore e licenze",
        "forceUpdate": "Forza Aggiornamento",
        "forceUpdateSubtitle": "Aggiorna tassi dall'API",
        "clearCache": "Cancella Cache",
        "clearCacheSubtitle": "Elimina dati salvati localmente",
        "cancel": "Annulla",
        "close": "Chiudi",
        "updatingRates": "Aggiornamento tassi...",
        "cacheCleared": "Cache cancellata",
        "developer": "Sviluppatore",
        "dataSource": "Fonte Dati",
        "legalNotice": "Avviso Legale",
        "legalNoticeText": "Questa applicazione NON rappresenta alcuna entità governativa o bancaria. Non siamo affiliati alla Banca Centrale del Venezuela. I dati sono ottenuti tramite un'API che consulta il sito ufficiale della BCV. L'uso delle informazioni è di esclusiva responsabilità dell'utente.",
        "openSourceLicenses": "Licenze Open Source",
        "version": "Versione",
        "becomePro": "Diventa PRO!",
        "proUser": "Sei un Utente PRO!",
        "getPro": "Ottieni PRO per",
        "oneTimePayment": "(Pagamento unico a vita)",
        "restorePurchases": "Ripristina Acquisti",
        "benefitAds": "Niente pubblicità",
        "benefitAdsDesc": "Goditi un'interfaccia pulita e senza interruzioni.",
        "benefitPdf": "Esportazione Istantanea",
        "benefitPdfDesc": "Genera PDF della cronologia senza guardare video pubblicitari.",
        "benefitSpeed": "Massima Velocità",
        "benefitSpeedDesc": "Navigazione più fluida e minor consumo di batteria.",
        "benefitSupport": "Supporta il progetto",
        "benefitSupportDesc": "Aiutaci a continuare a migliorare lo strumento.",
        "usd": "Dollari USA",
        "eur": "Euro",
        "ves": "Bolivar",
        "history": "Cronologia",
        "historyRates": "Cronologia Tassi",
        "start": "Inizio",
        "end": "Fine",
        "generatePdf": "Genera PDF",
        "watchAd": "Guarda pubblicità per sbloccare",
        "loadingAd": "Caricamento pubblicità...",
        "errorAd": "Errore caricamento",
        "today": "Oggi",
        "tomorrow": "Domani",
        "officialRate": "Tasso Ufficiale",
        "customRate": "Tasso Personalizzato",
        "convert": "Convertire"
    },
    "app_ru.arb": {
        "@@locale": "ru",
        "appTitle": "Калькулятор BCV",
        "settings": "Настройки",
        "general": "Общие",
        "storageNetwork": "Память и сеть",
        "storageNetworkSubtitle": "Управление кэшем и обновлениями",
        "language": "Язык",
        "information": "Информация",
        "aboutApp": "О приложении",
        "aboutAppSubtitle": "Версия, разработчик и лицензии",
        "forceUpdate": "Обновить принудительно",
        "forceUpdateSubtitle": "Обновить курсы через API",
        "clearCache": "Очистить кэш",
        "clearCacheSubtitle": "Удалить локальные данные",
        "cancel": "Отмена",
        "close": "Закрыть",
        "updatingRates": "Обновление курсов...",
        "cacheCleared": "Кэш очищен",
        "developer": "Разработчик",
        "dataSource": "Источник данных",
        "legalNotice": "Правовое уведомление",
        "legalNoticeText": "Это приложение НЕ представляет собой государственную или банковскую структуру. Мы не связаны с Центральным банком Венесуэлы. Данные получены через API с официального сайта BCV. Ответственность за использование информации лежит на пользователе.",
        "openSourceLicenses": "Лицензии ПО",
        "version": "Версия",
        "becomePro": "Стать PRO!",
        "proUser": "Вы PRO пользователь!",
        "getPro": "Купить PRO за",
        "oneTimePayment": "(Единовременный платеж)",
        "restorePurchases": "Восстановить",
        "benefitAds": "Без рекламы",
        "benefitAdsDesc": "Чистый интерфейс без отвлекающих факторов.",
        "benefitPdf": "Мгновенный экспорт",
        "benefitPdfDesc": "PDF без просмотра видеорекламы.",
        "benefitSpeed": "Макс. скорость",
        "benefitSpeedDesc": "Плавная навигация и экономия заряда.",
        "benefitSupport": "Поддержать проект",
        "benefitSupportDesc": "Помогите нам улучшать инструмент.",
        "usd": "Доллары США",
        "eur": "Евро",
        "ves": "Боливары",
        "history": "История",
        "historyRates": "История курсов",
        "start": "Начало",
        "end": "Конец",
        "generatePdf": "Создать PDF",
        "watchAd": "Смотреть рекламу",
        "loadingAd": "Загрузка...",
        "errorAd": "Ошибка",
        "today": "Сегодня",
        "tomorrow": "Завтра",
        "officialRate": "Офиц. курс",
        "customRate": "Свой курс",
        "convert": "Конвертировать"
    }
}

for filename, content in files.items():
    with open(f"lib/l10n/{filename}", "w", encoding="utf-8") as f:
        json.dump(content, f, ensure_ascii=False, indent=2)
