
import os

files = {
    "app_pt.arb": {
        "@@locale": "pt",
        "appTitle": "Calculadora BCV",
        "settings": "Configurações",
        "general": "Geral",
        "storageNetwork": "Armazenamento e Rede",
        "storageNetworkSubtitle": "Gerenciar cache e atualizações",
        "language": "Idioma",
        "information": "Informações",
        "aboutApp": "Sobre o App",
        "aboutAppSubtitle": "Versão, desenvolvedor e licenças",
        "forceUpdate": "Forçar Atualização",
        "forceUpdateSubtitle": "Atualizar taxas da API",
        "clearCache": "Limpar Cache",
        "clearCacheSubtitle": "Excluir dados armazenados localmente",
        "cancel": "Cancelar",
        "close": "Fechar",
        "updatingRates": "Atualizando taxas...",
        "cacheCleared": "Cache limpo",
        "developer": "Desenvolvedor",
        "dataSource": "Fonte de Dados",
        "legalNotice": "Aviso Legal",
        "legalNoticeText": "Este aplicativo NÃO representa nenhuma entidade governamental ou bancária. Não temos afiliação com o Banco Central da Venezuela. Os dados são obtidos por meio de uma API que consulta o site oficial do BCV. O uso das informações é de responsabilidade exclusiva do usuário.",
        "openSourceLicenses": "Licenças de Código Aberto",
        "version": "Versão",
        "becomePro": "Torne-se PRO!",
        "proUser": "Você é um Usuário PRO!",
        "getPro": "Obter PRO por",
        "oneTimePayment": "(Pagamento único vitalício)",
        "restorePurchases": "Restaurar Compras",
        "benefitAds": "Sem anúncios",
        "benefitAdsDesc": "Desfrute de uma interface limpa e sem interrupções.",
        "benefitPdf": "Exportação Instantânea",
        "benefitPdfDesc": "Gere PDFs do seu histórico sem assistir anúncios.",
        "benefitSpeed": "Velocidade Máxima",
        "benefitSpeedDesc": "Navegação mais fluida e menor consumo de bateria.",
        "benefitSupport": "Apoie o projeto",
        "benefitSupportDesc": "Ajude-nos a continuar melhorando a ferramenta.",
        "usd": "Dólares",
        "eur": "Euros",
        "ves": "Bolívares",
        "history": "Histórico",
        "historyRates": "Histórico de Taxas",
        "start": "Início",
        "end": "Fim",
        "generatePdf": "Gerar PDF",
        "watchAd": "Assista ao anúncio para desbloquear",
        "loadingAd": "Carregando anúncio...",
        "errorAd": "Erro ao carregar anúncio",
        "today": "Hoje",
        "tomorrow": "Amanhã",
        "officialRate": "Taxa Oficial",
        "customRate": "Taxa Personalizada",
        "convert": "Converter"
    },
    "app_fr.arb": {
        "@@locale": "fr",
        "appTitle": "Calculatrice BCV",
        "settings": "Paramètres",
        "general": "Général",
        "storageNetwork": "Stockage et Réseau",
        "storageNetworkSubtitle": "Gérer le cache et les mises à jour",
        "language": "Langue",
        "information": "Informations",
        "aboutApp": "À propos de l'application",
        "aboutAppSubtitle": "Version, développeur et licences",
        "forceUpdate": "Forcer la mise à jour",
        "forceUpdateSubtitle": "Mettre à jour les taux depuis l'API",
        "clearCache": "Vider le cache",
        "clearCacheSubtitle": "Supprimer les données stockées localement",
        "cancel": "Annuler",
        "close": "Fermer",
        "updatingRates": "Mise à jour des taux...",
        "cacheCleared": "Cache vidé",
        "developer": "Développeur",
        "dataSource": "Source de données",
        "legalNotice": "Mentions Légales",
        "legalNoticeText": "Cette application NE représente AUCUNE entité gouvernementale ou bancaire. Nous ne sommes pas affiliés à la Banque Centrale du Venezuela. Les données sont obtenues via une API qui consulte le site officiel de la BCV. L'utilisation des informations relève de la seule responsabilité de l'utilisateur.",
        "openSourceLicenses": "Licences Open Source",
        "version": "Version",
        "becomePro": "Devenez PRO !",
        "proUser": "Vous êtes utilisateur PRO !",
        "getPro": "Obtenir PRO pour",
        "oneTimePayment": "(Paiement unique à vie)",
        "restorePurchases": "Restaurer les achats",
        "benefitAds": "Plus de publicités",
        "benefitAdsDesc": "Profitez d'une interface propre et sans interruptions.",
        "benefitPdf": "Export Instantané",
        "benefitPdfDesc": "Générez des PDF de votre historique sans voir de publicités.",
        "benefitSpeed": "Vitesse Maximale",
        "benefitSpeedDesc": "Navigation plus fluide et consommation de batterie réduite.",
        "benefitSupport": "Soutenez le projet",
        "benefitSupportDesc": "Aidez-nous à améliorer l'outil.",
        "usd": "Dollars US",
        "eur": "Euros",
        "ves": "Bolivars",
        "history": "Historique",
        "historyRates": "Historique des Taux",
        "start": "Début",
        "end": "Fin",
        "generatePdf": "Générer PDF",
        "watchAd": "Regarder une pub pour débloquer",
        "loadingAd": "Chargement...",
        "errorAd": "Erreur de chargement",
        "today": "Aujourd'hui",
        "tomorrow": "Demain",
        "officialRate": "Taux Officiel",
        "customRate": "Taux Personnalisé",
        "convert": "Convertir"
    }
}

import json

for filename, content in files.items():
    with open(f"lib/l10n/{filename}", "w", encoding="utf-8") as f:
        json.dump(content, f, ensure_ascii=False, indent=2)
